title: The Learning Landing Zone
author: GitHub Edu Account
email: not_real@some-random-fake-domain.example
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Nothing to see here. Move Along!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
